# Generated by Django 3.1 on 2020-09-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMetaData',
        ),
    ]
