# Generated by Django 2.2 on 2019-12-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fake_field',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fake_field',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fake_field',
        ),
    ]
