# Generated by Django 2.2 on 2020-03-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_pedido_seleccionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='seleccionado',
        ),
    ]
