# Generated by Django 2.2 on 2020-04-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tag',
            field=models.CharField(default='Otros', max_length=25, unique=True),
        ),
    ]
