# Generated by Django 3.1 on 2020-11-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_auto_20200407_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to='producto'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, default='default_tienda_image.jpg', null=True, upload_to='tienda'),
        ),
    ]
