# Generated by Django 3.1 on 2020-11-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20201111_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='correo',
            field=models.EmailField(default='noemail@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='tienda',
            name='numero_de_cuenta',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
